### PR TITLE
Add provider to app.php

### PR DESCRIPTION
**Pull request by sahilpurav**
I had to explicitly add ```Bavix\XHProf\XHProfServiceProvider::class,``` in the app.php provider in order to get this working.

### CODE REVIEW

**Comment by rez1dent3** [comment]
@sahilpurav Hello. It's too much. Since laravel 5.5 there is automatic loading of providers using composer.
https://github.com/bavix/laravel-xhprof/blob/690f352612855d8e8c603d40771637a57abf3868/composer.json#L31

**Comment by rez1dent3** [comment]
@khanakia Since laravel 5.5, providers are automatically added via composer. Adding an additional provider can be detrimental to the package. Are you using lumen?

**Comment by khanakia** [comment]
We are using laravel 5.3. Anyway i download the repo from github and manually included. As it does not works for laravel 5.3 while using with composer install gives laravel 5.5 error.

**Comment by rez1dent3** [comment]
@khanakia Yes, it is logical. I support since 5.5+.

If you wish, add support for laravel 5.3+ in composer.json and add "relevant for versions below 5.5" in paragraph 10, then I will accept PR.

**Pull request closed without merging**
